name       : gifski
version    : 1.7.0
release    : 8
source     :
    - https://github.com/ImageOptim/gifski/archive/refs/tags/1.7.0.tar.gz : f9d66778d763f2391fa626261d24815799f1dfe61ce9ee0cc5637692172db29d
homepage   : https://gif.ski/
license    : AGPL-3.0-or-later
component  : multimedia.library
summary    : GIF encoder based on libimagequant
description: |
    gifski converts video frames to GIF animations using pngquant's fancy features for efficient cross-frame palettes and temporal dithering. It produces animated GIFs that use thousands of colors per frame.
networking : yes
builddeps  :
    - pkgconfig(libavutil)
    - cargo
    - llvm-clang-devel
build      : |
    cargo build --release --features=openmp,video
install    : |
    install -Dm00755 target/release/gifski $installdir/usr/bin/gifski
