name       : gifski
version    : 1.8.0
release    : 9
source     :
    - https://github.com/ImageOptim/gifski/archive/refs/tags/1.8.0.tar.gz : 77bbb6736217f0fe43e2c2b49855fe22e32d41f77b5e715950b7a52903518f9c
homepage   : https://gif.ski/
license    : AGPL-3.0-or-later
component  : multimedia.library
summary    : GIF encoder based on libimagequant
description: |
    gifski converts video frames to GIF animations using pngquant's fancy features for efficient cross-frame palettes and temporal dithering. It produces animated GIFs that use thousands of colors per frame.
networking : yes
builddeps  :
    - pkgconfig(libavutil)
    - cargo
    - llvm-clang-devel
build      : |
    cargo build --release --features=openmp,video
install    : |
    install -Dm00755 target/release/gifski $installdir/usr/bin/gifski
