name       : gifski
version    : 0.8.4
release    : 2
source     :
    - https://github.com/ImageOptim/gifski/archive/0.8.4.tar.gz : e78da4306f01bf4070d7904066f5253058866a9888ca59fc3a08a2a547607b5c
license    : AGPL-3.0-or-later
component  : multimedia.library
summary    : GIF encoder based on libimagequant. Squeezes maximum possible quality from the awful GIF format
description: |
    GIF encoder based on libimagequant. Squeezes maximum possible quality from the awful GIF format.
networking : yes
builddeps  :
    - cargo
    - ffmpeg-devel
    - llvm-clang-devel
build      : |
    cargo build --release --features=video,openmp
install    : |
    install -Dm755 target/release/gifski $installdir/usr/bin/gifski
