name       : gifski
version    : 0.8.7
release    : 4
source     :
    - https://github.com/ImageOptim/gifski/archive/0.8.7.tar.gz : e8d8d2fdb816953315989b3ecf39ac88f33b8c49aa7c79a0df8f53b4032755ab
license    : AGPL-3.0-or-later
component  : multimedia.library
summary    : GIF encoder based on libimagequant. Squeezes maximum possible quality from the awful GIF format
description: |
    GIF encoder based on libimagequant. Squeezes maximum possible quality from the awful GIF format.
networking : yes
builddeps  :
    - cargo
    - llvm-clang-devel
build      : |
    cargo build --release --features=openmp
install    : |
    install -Dm00755 target/release/gifski $installdir/usr/bin/gifski
