name       : gifski
version    : 0.8.0
release    : 1
source     :
    - https://github.com/ImageOptim/gifski/archive/0.8.0.tar.gz : f3cab822dd41de17ba4fdc3b8d379b469404573b1a4adcb5f9c9385a7a927760
license    : AGPL-3.0
component  : multimedia.library
summary    : GIF encoder based on libimagequant. Squeezes maximum possible quality from the awful GIF format.
description: |
    GIF encoder based on libimagequant. Squeezes maximum possible quality from the awful GIF format.
networking : yes
builddeps  :
    - cargo
    - ffmpeg-devel
    - llvm-clang-devel
build      : |
    cargo build --release --features=video,openmp
install    : |
    install -Dm755 target/release/gifski $installdir/usr/bin/gifski
