name       : gifski
version    : 1.4.3
release    : 5
source     :
    - https://github.com/ImageOptim/gifski/archive/refs/tags/1.4.3.tar.gz : 74b98ede664e3da420ead70e3da1dfeb1a6e33545a618124e6b49da8f399902f
license    : AGPL-3.0-or-later
component  : multimedia.library
summary    : GIF encoder based on libimagequant. Squeezes maximum possible quality from the awful GIF format
description: |
    GIF encoder based on libimagequant. Squeezes maximum possible quality from the awful GIF format.
networking : yes
builddeps  :
    - cargo
    - llvm-clang-devel
build      : |
    cargo build --release --features=openmp
install    : |
    install -Dm00755 target/release/gifski $installdir/usr/bin/gifski
