name       : gifski
version    : 0.8.5
release    : 3
source     :
    - https://github.com/ImageOptim/gifski/archive/0.8.5.tar.gz : 0c4f946e873e26777423e1bab37392220aec9382ae818866d2e3a52b3c976cf1
license    : AGPL-3.0-or-later
component  : multimedia.library
summary    : GIF encoder based on libimagequant. Squeezes maximum possible quality from the awful GIF format
description: |
    GIF encoder based on libimagequant. Squeezes maximum possible quality from the awful GIF format.
networking : yes
builddeps  :
    - cargo
    - llvm-clang-devel
build      : |
    cargo build --release --features=openmp
install    : |
    install -Dm00755 target/release/gifski $installdir/usr/bin/gifski
