name       : gifski
version    : 1.6.4
release    : 7
source     :
    - https://github.com/ImageOptim/gifski/archive/refs/tags/1.6.4.tar.gz : 1bcc1bdbfdb206f44de75662ee5a8a8c61d336c04cb62457e02c9fa8456f3928
homepage   : https://gif.ski/
license    : AGPL-3.0-or-later
component  : multimedia.library
summary    : GIF encoder based on libimagequant
description: |
    gifski converts video frames to GIF animations using pngquant's fancy features for efficient cross-frame palettes and temporal dithering. It produces animated GIFs that use thousands of colors per frame.
networking : yes
builddeps  :
    - pkgconfig(libavutil)
    - cargo
    - llvm-clang-devel
build      : |
    cargo build --release --features=openmp,video
install    : |
    install -Dm00755 target/release/gifski $installdir/usr/bin/gifski
